services:
  - type: web
    name: nosso-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_comercial:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads_comercial
      sizeGB: 1
